[package]

name = "mio"
# When releasing to crates.io:
# - Update html_root_url.
# - Update CHANGELOG.md.
# - Update doc URL.
# - Create git tag
version = "0.6.21"
license = "MIT"
authors = ["Carl Lerche <me@carllerche.com>"]
description = "Lightweight non-blocking IO"
documentation = "https://docs.rs/mio/0.6.21/mio/"
homepage = "https://github.com/carllerche/mio"
repository = "https://github.com/carllerche/mio"
readme = "README.md"
keywords = ["io", "async", "non-blocking"]
categories = ["asynchronous"]
exclude = [".gitignore", ".travis.yml", "deploy.sh"]

[features]
with-deprecated = []
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "sgx_trts", "sgx_libc"]

[dependencies]
log = { git = "https://github.com/OverOrion/log-sgx", branch = "teaclave-v1.1.6-testing"}
slab = { git = "https://github.com/OverOrion/slab-sgx", branch = "teaclave-v1.1.6-testing"}
net2 = { git = "https://github.com/OverOrion/net2-rs-sgx", branch = "teaclave-v1.1.6-testing"}
iovec = { git = "https://github.com/OverOrion/iovec-sgx", branch = "teaclave-v1.1.6-testing"}

[target.'cfg(not(all(target_env = "sgx", target_vendor = "mesalock")))'.dependencies]
sgx_tstd = { git = 'https://github.com/apache/incubator-teaclave-sgx-sdk.git', branch = 'v1.1.6-testing',  features = [
  "net",
], optional = true }
sgx_libc = { git = 'https://github.com/apache/incubator-teaclave-sgx-sdk.git', branch = 'v1.1.6-testing', optional = true }
sgx_trts = { git = 'https://github.com/apache/incubator-teaclave-sgx-sdk.git', branch = 'v1.1.6-testing', optional = true }

#[target.'cfg(target_os = "fuchsia")'.dependencies]
#fuchsia-zircon = "0.3.2"
#fuchsia-zircon-sys = "0.3.2"

#[target.'cfg(unix)'.dependencies]
#libc   = "0.2.42"

#[target.'cfg(windows)'.dependencies]
#winapi = "0.2.6"
#miow   = "0.2.1"
#kernel32-sys = "0.2"

[dev-dependencies]
#env_logger = { version = "0.4.0", default-features = false }
#tempdir    = "0.3.4"
#bytes      = "0.3.0"

[[test]]
name = "test"
path = "test/mod.rs"
